### ISSUE TITLE
Upload existing files to Teams channel

### ISSUE THREAD

**Issue by JuanKRuiz** [jwendl/lob-application-accelerator#13]

**Comment by tessmichi** [comment]
using the sharepoint list that's automatically created when a channel is made

**Comment by jwendl** [comment]
We need to consider the best approach in how to upload the file to the storage account so that we can point to it.

**Comment by tessmichi** [comment]
we can use the sharepoint list that's created when a team is created. we just need to access it. essentially it maps to the Files tab, and it would be cool if we can programatically save files to that

**Comment by tessmichi** [comment]
possibly start with the file source being a local file, in the console app that @allantargino  made

**Comment by jwendl** [comment]
Or maybe we can use Graph to access one drive for business as the source of the files with references?

**Comment by jwendl** [comment]
We decided to use the graph "copy" functionality to copy from OneDrive for Business to the SharePoint list for the teams channel.
