### ISSUE TITLE
Create a TokenService to handle token refresh, etc

### ISSUE THREAD

**Issue by ianisms** [jwendl/lob-application-accelerator#22]

**Comment by tessmichi** [comment]
Goals:
- replace REST with using the MSAL library
- use TokenCache table storage
- only 1 single public method, "GetValidTokenAsync" that obfuscates any need for refresh tokens. accepts: AuthHeaderValue and scopes

**Comment by tessmichi** [comment]
Left TODO
- update TokenManager to use the service
- write tests

**Comment by tessmichi** [comment]
writing tests now

**Comment by tessmichi** [comment]
closed by #56
